server:
  port: 8084

spring:
  application:
    name: commande-service

  datasource:
    url: jdbc:mysql://localhost:3306/utilisateurdb
    username: root
    password: ""                      # même si vide, précisez-le
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
